# [config]
# status = "uwu, I'm a status!"

# [[config.linkers]]
# title = "owo"
# description = "omg it's the site!"
# site_name = "owo.com"
# image_url = "https://m.media-amazon.com/images/I/A13usaonutL._CLa%7C2140%2C2000%7C61Rz1mXRMPL.png%7C0%2C0%2C2140%2C2000%2B0.0%2C0.0%2C2140.0%2C2000.0_AC_UY1000_.png"
# colour = "#fff"
# url = "https://cdn.devgoldy.xyz/ricky.webm"

# [[config.projects]]
# name = "📚 AGHPB API"
# description = "API that spits out anime girls holding programming books."
# git = "https://github.com/THEGOLDENPRO/aghpb_api"
# image = "https://github.com/THEGOLDENPRO/aghpb_api/raw/main/assets/screenshot_1.png"